version: '3.8'

volumes:
  kong_db_data: {}
  konga_db_data: {}

networks:
  kong-net:
    driver: bridge

x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong-db
  KONG_PG_DATABASE: kong
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kong


services:
  # PostgreSQL for Kong
  kong-db:
    container_name: kong-db
    image: 192.168.5.6/mirrors/postgres:14
    restart: on-failure
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 10s
      retries: 10

  # Kong migrations bootstrap
  kong-bootstrap:
    image: 192.168.5.6/mirrors/kong:3.9.1
    container_name: kong-bootstrap
    networks:
      - kong-net
    depends_on:
      kong-db:
        condition: service_healthy
    restart: on-failure
    environment:
      <<: *kong-env
    command: kong migrations bootstrap

  # Kong OSS
  kong:
    image: 192.168.5.6/mirrors/kong:3.9.1
    container_name: kong
    restart: on-failure
    networks:
      - kong-net
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  # Konga GUI
  kong-manager:
    image: kong-manager:1.0
    container_name: kong-manager
    environment:
      ADMIN_API_URL: "http://localhost:8001"
      ADMIN_API_PORT: 8001
      ADMIN_API_SSL_PORT: 8444
      ADMIN_GUI_PATH: "/"
      ANONYMOUS_REPORTS: "false"
    ports:
      - "1337:80"
